language: node_js

cache:
  directories:
  - node_modules
  - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn buildProd

notifications:
  email:
    reciepients:
      - alextorre0427@gmail.com
    on_success: always
    on_failure: always
  
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: c203d8ae-0015-4829-b168-32938e4e69f6
  app: platzi-store-backend-atr
  on:
    repo: alextorrer/platzi-store-backend